"""Shared helpers for advanced experiment result analysis.

These functions keep the advanced dashboard script small and reusable.  The
input is always the official CSV generated by ``batch_experiment.py``; no demo
or fake data is created here.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import pandas as pd
from pandas.errors import EmptyDataError


REQUIRED_COLUMNS = [
    "difficulty",
    "scale",
    "strategy",
    "total_score",
    "completed_tasks",
    "timeout_tasks",
    "total_distance",
]

OPTIONAL_CHARGING_COLUMNS = [
    "charging_times",
    "charging_requests",
    "charging_queue_events",
    "max_queue_length",
    "total_charging_wait_time",
]

MIN_EXPECTED_ROWS = 48

DIFFICULTY_PRIORITY = ["easy", "medium", "hard"]
SCALE_PRIORITY = ["small", "medium", "large", "extra_large"]
STRATEGY_PRIORITY = [
    "nearest",
    "largest",
    "energy_aware_hybrid",
    "genetic_algorithm",
]


def load_experiment_results(csv_path: Path | str) -> pd.DataFrame:
    """Load official experiment CSV and stop clearly if it is unavailable."""

    csv_path = Path(csv_path)
    try:
        df = pd.read_csv(csv_path)
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            "results/experiment_results.csv not found. "
            "Please run python3 batch_experiment.py all --quiet first."
        ) from exc
    except EmptyDataError as exc:
        raise ValueError(
            "results/experiment_results.csv is empty. "
            "Please run python3 batch_experiment.py all --quiet first."
        ) from exc

    return validate_experiment_data(df)


def validate_experiment_data(df: pd.DataFrame) -> pd.DataFrame:
    """Validate required columns and make numeric columns safe for plotting."""

    if df.empty:
        raise ValueError(
            "experiment_results.csv has no rows. "
            "Please run python3 batch_experiment.py all --quiet first."
        )

    if len(df) < MIN_EXPECTED_ROWS:
        raise ValueError(
            f"experiment_results.csv has only {len(df)} rows; expected at least {MIN_EXPECTED_ROWS} "
            "for the official 4 scales x 3 difficulties x 4 strategies experiment. "
            "Please run python3 batch_experiment.py all --quiet first."
        )

    missing = [column for column in REQUIRED_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(f"experiment_results.csv is missing required columns: {missing}")

    df = df.copy()
    numeric_columns = [
        column
        for column in REQUIRED_COLUMNS + OPTIONAL_CHARGING_COLUMNS
        if column in df.columns and column not in {"difficulty", "scale", "strategy"}
    ]
    for column in numeric_columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    nan_columns = [column for column in REQUIRED_COLUMNS if df[column].isna().any()]
    if nan_columns:
        raise ValueError(f"Required columns contain NaN values: {nan_columns}")

    optional_nan_columns = [
        column for column in OPTIONAL_CHARGING_COLUMNS if column in df.columns and df[column].isna().any()
    ]
    if optional_nan_columns:
        print(f"Warning: optional columns contain NaN and will be filled with 0: {optional_nan_columns}")
        df[optional_nan_columns] = df[optional_nan_columns].fillna(0)

    return df


def ensure_output_dir(path: Path | str) -> Path:
    """Create output directory and return it as a Path."""

    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


def _ordered_values(values: Iterable[str], priority: list[str]) -> list[str]:
    unique_values = list(dict.fromkeys(str(value) for value in values))
    known = [value for value in priority if value in unique_values]
    extra = sorted(value for value in unique_values if value not in priority)
    return known + extra


def get_strategy_order(df: pd.DataFrame) -> list[str]:
    return _ordered_values(df["strategy"].dropna().tolist(), STRATEGY_PRIORITY)


def get_difficulty_order(df: pd.DataFrame) -> list[str]:
    return _ordered_values(df["difficulty"].dropna().tolist(), DIFFICULTY_PRIORITY)


def get_scale_order(df: pd.DataFrame) -> list[str]:
    return _ordered_values(df["scale"].dropna().tolist(), SCALE_PRIORITY)


def normalize_metric(series: pd.Series, higher_is_better: bool = True) -> pd.Series:
    """Normalize a metric to 0..1, reversing it for lower-is-better metrics."""

    series = pd.to_numeric(series, errors="coerce").fillna(0)
    min_value = series.min()
    max_value = series.max()
    if max_value == min_value:
        return pd.Series([1.0] * len(series), index=series.index)

    normalized = (series - min_value) / (max_value - min_value)
    if not higher_is_better:
        normalized = 1.0 - normalized
    return normalized


def save_figure(fig, output_path: Path | str, dpi: int = 220) -> None:
    """Save a Matplotlib figure with consistent spacing and close it."""

    output_path = Path(output_path)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def shorten_strategy_name(name: str) -> str:
    labels = {
        "nearest": "Nearest",
        "largest": "Largest",
        "energy_aware_hybrid": "Hybrid",
        "genetic_algorithm": "GA",
    }
    return labels.get(str(name), str(name).replace("_", " ").title())


def aggregate_by_strategy(df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate major KPIs by strategy for summary tables and charts."""

    agg_map = {
        "total_score": "mean",
        "completed_tasks": "mean",
        "timeout_tasks": "mean",
        "total_distance": "mean",
    }
    for column in OPTIONAL_CHARGING_COLUMNS:
        if column in df.columns:
            if column == "max_queue_length":
                agg_map[column] = "max"
            else:
                agg_map[column] = "sum"

    summary = df.groupby("strategy", as_index=False).agg(agg_map)
    summary["strategy_label"] = summary["strategy"].map(shorten_strategy_name)
    ordered = get_strategy_order(df)
    summary["_order"] = summary["strategy"].apply(lambda value: ordered.index(value) if value in ordered else 999)
    summary = summary.sort_values("_order").drop(columns="_order")
    return summary


def write_html_report(
    output_path: Path | str,
    csv_path: Path | str,
    df: pd.DataFrame,
    summary_df: pd.DataFrame,
    figures: list[tuple[str, str] | tuple[str, str, str]],
) -> None:
    """Write a dependency-free HTML index linking all generated analysis PNGs."""

    output_path = Path(output_path)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    strategies = ", ".join(shorten_strategy_name(s) for s in get_strategy_order(df))
    difficulties = ", ".join(get_difficulty_order(df))
    scales = ", ".join(get_scale_order(df))
    summary_html = summary_df.round(2).to_html(index=False, classes="summary-table")

    figure_blocks = []
    for figure in figures:
        if len(figure) == 3:
            file_name, caption, description = figure
        else:
            file_name, caption = figure
            description = ""
        figure_blocks.append(
            f"""
            <section class="figure-card">
                <h2>{caption}</h2>
                <img src="{file_name}" alt="{caption}">
                <p>{description}</p>
            </section>
            """
        )

    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>新能源物流车队调度实验分析</title>
    <style>
        body {{
            margin: 0;
            padding: 32px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
            background: #f5f7fb;
            color: #1f2937;
        }}
        .page {{
            max-width: 1180px;
            margin: 0 auto;
        }}
        h1 {{
            margin-bottom: 8px;
            font-size: 30px;
        }}
        .meta {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
            gap: 10px 24px;
            padding: 18px 20px;
            background: white;
            border: 1px solid #d8e0ea;
            border-radius: 10px;
            margin: 20px 0;
        }}
        .summary-table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            margin: 12px 0 28px;
            font-size: 14px;
        }}
        .summary-table th, .summary-table td {{
            border: 1px solid #d8e0ea;
            padding: 8px 10px;
            text-align: right;
        }}
        .summary-table th:first-child, .summary-table td:first-child,
        .summary-table th:last-child, .summary-table td:last-child {{
            text-align: left;
        }}
        .figure-card {{
            background: white;
            border: 1px solid #d8e0ea;
            border-radius: 10px;
            margin: 24px 0;
            padding: 18px;
        }}
        .figure-card h2 {{
            margin: 0 0 12px;
            font-size: 20px;
        }}
        img {{
            max-width: 100%;
            display: block;
            margin: 0 auto;
        }}
        code {{
            background: #eef2f7;
            padding: 2px 5px;
            border-radius: 4px;
        }}
    </style>
</head>
<body>
<main class="page">
    <h1>新能源物流车队协同调度实验分析</h1>
    <p>本页面由 <code>visualization/advanced_analysis.py</code> 自动生成，用于报告和答辩展示。</p>
    <div class="meta">
        <div><strong>数据源：</strong>{csv_path}</div>
        <div><strong>生成时间：</strong>{generated_at}</div>
        <div><strong>实验行数：</strong>{len(df)}</div>
        <div><strong>策略：</strong>{strategies}</div>
        <div><strong>难度：</strong>{difficulties}</div>
        <div><strong>规模：</strong>{scales}</div>
    </div>
    <h2>策略 KPI 汇总表</h2>
    {summary_html}
    {''.join(figure_blocks)}
</main>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
